### ISSUE TITLE
onedrive gui stop syncing without a visible reason

### ISSUE THREAD

**Issue by karolszk** [bpozdena/OneDriveGUI#150]
immediately (few seconds) after I manually started syncing folders (green icon) syncing is stopped (red icon). Problem is repeatable. However syncing manually by onedrive -m works without any issues.

I use the latest version of the mainstream onedrive program: onedrive v2.4.25-13-g1a88d33
and the latest version of OneDriveGUI too:

commit bc9bf3ee946b8fc2905671ea852cb25b740b09f6 (HEAD -> main, origin/main, origin/HEAD)
Merge: 92d18f1 021f45e
Author: Boris Pozdena <boris@pozdena.eu>
Date:   Fri Dec 22 10:34:46 2023 +0100

    Merge pull request #129 from sschuberth/patch-1
    
    README: Fix install instructions

**Comment by liamrahum** [comment]
How long have you been experiencing this? I've noticed this a few days ago but now it seems like a problem with onedrivegui itself.

**Comment by bpozdena** [comment]
Can you please start the GUI from terminal, start sync in the GUI and then share the outputs from terminal? Please mask any personal data, but keep the rest unchanged.

**Comment by liamrahum** [comment]
```2024-01-11 19:53:41,695 [onedrivegui:2100][fn=read_stdout][INFO] - [Liam] Configuration file successfully loaded
2024-01-11 19:53:41,696 [onedrivegui:2100][fn=read_stdout][INFO] - [Liam] The use of --resync will remove your local 'onedrive' client state, thus no record will exist regarding your current 'sync status'
2024-01-11 19:53:41,696 [onedrivegui:2100][fn=read_stdout][INFO] - [Liam] This has the potential to overwrite local versions of files with potentially older versions downloaded from OneDrive which can lead to data loss
2024-01-11 19:53:41,696 [onedrivegui:2100][fn=read_stdout][INFO] - [Liam] If in-doubt, backup your local data first before proceeding with --resync```

**Comment by liamrahum** [comment]
Note that I added "resync" as the client said it was required.

**Comment by karolszk** [comment]
2024-01-12 08:43:01,564 [OneDriveGUI.py:2100][fn=read_stdout][INFO] - [karolm] Processing xxxxxxxx
2024-01-12 08:43:01,564 [OneDriveGUI.py:2100][fn=read_stdout][INFO] - [karolm] The file has not changed
2024-01-12 08:43:01,564 [OneDriveGUI.py:2100][fn=read_stdout][INFO] - [karolm] Uploading new items of ~/OneDrive
Traceback (most recent call last):
  File "/home/karolm/prg/OneDriveGUI/src/OneDriveGUI.py", line 2082, in run
    self.read_stdout()
  File "/home/karolm/prg/OneDriveGUI/src/OneDriveGUI.py", line 2098, in read_stdout
    stdout = self.onedrive_process.stdout.readline().strip()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb3 in position 83: invalid start byte
2024-01-12 08:43:02,121 [OneDriveGUI.py:2572][fn=<lambda>][INFO] - finished worker karolm
2024-01-12 08:43:02,122 [OneDriveGUI.py:2035][fn=stop_worker][INFO] - [karolm] Waiting for worker to finish...
2024-01-12 08:43:02,139 [OneDriveGUI.py:2039][fn=stop_worker][INFO] - [karolm] Quitting thread
2024-01-12 08:43:02,139 [OneDriveGUI.py:2042][fn=stop_worker][INFO] - [karolm] Removing thread info
2024-01-12 08:43:02,139 [OneDriveGUI.py:2045][fn=stop_worker][INFO] - [GUI] Remaining running workers: {}

**Comment by bpozdena** [comment]
> ```
> 2024-01-11 19:53:41,696 [onedrivegui:2100][fn=read_stdout][INFO] - [Liam] The use of --resync will remove your local 'onedrive' client state, thus no record will exist regarding your current 'sync status'
> 2024-01-11 19:53:41,696 [onedrivegui:2100][fn=read_stdout][INFO] - [Liam] This has the potential to overwrite local versions of files with potentially older versions downloaded from OneDrive which can lead to data loss
> 2024-01-11 19:53:41,696 [onedrivegui:2100][fn=read_stdout][INFO] - [Liam] If in-doubt, backup your local data first before proceeding with --resync```
> ```

I already fixed this in the 1.10alpha branch via https://github.com/bpozdena/OneDriveGUI/commit/50597259759404110ee415cc03bcf057a0736360#diff-b9590cd269a4e0995f8e177e344cedb69b5df7f4eec0e5463308a9fe93dadbf8R2540 . But it's strange you're getting this issue with onedrive client v2.4. can you share the version of your client?

**Comment by bpozdena** [comment]
> in read_stdout stdout = self.onedrive_process.stdout.readline().strip() ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "", line 322, in decode UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb3 in position 83: invalid start byte 2024-01-12 

Thanks I'll try to improve handling of the decoding error.

**Comment by bpozdena** [comment]
I could not reproduce either of the issues, but I made some changes that should theoretically fix them.
Please test from branch `fix_150` or with this AppImage [OneDriveGUI-1.0.3_fix150-x86_64.AppImage](https://github.com/bpozdena/OneDriveGUI/releases/download/v1.0.3/OneDriveGUI-1.0.3_fix150-x86_64.AppImage) .

@karolszk and @liamrahum please confirm if your issues got resolved.

**Comment by karolszk** [comment]
Hello, thank you, I've switched to fix_150, the problem unfortunately still exists. The log error:

2024-01-15 08:53:02,487 [OneDriveGUI.py:2100][fn=read_stdout][INFO] - [karolm] Uploading new items of ~/OneDrive
Traceback (most recent call last):
  File "/home/karolm/prg/OneDriveGUI/src/OneDriveGUI.py", line 2082, in run
    self.read_stdout()
  File "/home/karolm/prg/OneDriveGUI/src/OneDriveGUI.py", line 2098, in read_stdout
    stdout = self.onedrive_process.stdout.readline().strip()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb3 in position 83: invalid start byte

**Comment by bpozdena** [comment]
@karolszk Could it not be something wrong with your Python environment? Please try the AppImage (run it from terminal to see debug logs).

**Comment by karolszk** [comment]
Hi @bpozdena you are right. The problem was a letter 'ł' in filename (byte OxB3) in CP1250 encoding. I have checked all my OneDrive directory and found it. Renamed, and OneDriveGUI works as usual. 
Tested on fix_150 and main too. 
Thank you.

**Comment by abraunegg** [comment]
> Hi @bpozdena you are right I have checked my env. The problem was a letter 'ł' in filename (byte OxB3) in CP1250 encoding. I have checked all my OneDrive directory and found it. Renamed, and OneDriveGUI works as usual. Tested on fix_150 and main too. Thank you.

In v2.5.x there is greater checking for ASCII Control Characters that will occur. Files|Folders that do not conform to this will generate an error and will not be uploaded.
